### ISSUE TITLE
Problem set one issue

### ISSUE THREAD

**Issue by TheophilusZhang** [prog4biol/pfb2019#66]
Hello,

This is such a helpful site. I just too bad at coding. I was doing the problem set one. I download the file with command 
cd ~
curl -0 https://raw.githubusercontent.com/prog4biol/pfb2019/master/files/cuffdiff.txt

and there were a long list running automatically, after it's done, I run 
cd ~
grep Chr7 cuffdiff.txt 
it says 
grep: cuffdiff.txt: No such file or directory
is there anything I did wrong?

Thanks again for your generous help

**Comment by srobb1** [comment]
Hello @TheophilusZhang,
Could you please paste the exact output you get from the `curl -0 https://raw.githubusercontent.com/prog4biol/pfb2019/master/files/cuffdiff.txt` command? 

Here is what I see and expect to see if `curl` is working on your machine 
```
curl -O https://raw.githubusercontent.com/prog4biol/pfb2019/master/files/cuffdiff.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1087k  100 1087k    0     0   563k      0  0:00:01  0:00:01 --:--:--  562k
```

Sofia

**Comment by TheophilusZhang** [comment]
Hi Sofia,

I copy and pasted your code today and it worked! I checked the spelling of code between us, but didn't find any mistake. I have no idea why it worked today but not work yesterday. But anyway, the point is let it run and do the problem set. Thank you very much!

Bo

**Comment by srobb1** [comment]
Great!! Keep it up! Post more questions as you have them.

Sofia
