### ISSUE TITLE
problem set 1 question

### ISSUE THREAD

**Issue by TheophilusZhang** [prog4biol/pfb2019#67]
Hello,

I got another simple question in problem set 1 :p I created the directory"problemsets" under my home directory, and I go to the problemsets directory and check it by using pwd. I download the file by 
curl -0 https://raw.githubusercontent.com/prog4biol/pfb2019/master/files/sequences.nt.fa
and the terminal shows two lists of sequence, but seems the file is not downloaded in the problemsets. When I tryied wc sequences.nt.fa, the terminal says "No such file or directory" and when I use ls -F, the preblemsets directory shows nothing...
I guess I made some basic mistake.

Thank you,
Bo

**Comment by srobb1** [comment]
Hi Bo,
Can you use the `history` command to send me the steps you took? Double check that you did these in this order :
```
cd ~
mkdir problemsets
cd problemsets
curl -0 https://raw.githubusercontent.com/prog4biol/pfb2019/master/files/sequences.nt.fa 
wc sequences.nt.fa
```

Sofia

**Comment by srobb1** [comment]
Bo,
I copied your curl command in my reply. @procho just noticed that I have a -0 [ZERO] not a -O [oh] in the command. Since I copied your command, you likely have a ZERO as well.  Check this out!

Sofia and Simon

**Comment by TheophilusZhang** [comment]
Agh...I thought it is zero. Now I get it worked. I think I won't have same type of question in the future:) Thank you very much!

Bo
