### ISSUE TITLE
Question in Problemset 2

### ISSUE THREAD

**Issue by TheophilusZhang** [prog4biol/pfb2019#68]
Hello,

I have a small question in problem set 2 question 15.
I created the file by vi named oops,
I saw it in my directory which linked to remote depository, but when I tried git rm oops,
the system shows:
fatal: pathspec 'oops' did not match any files, I tried include the path but it shows the same error message...

Thank you for your help!
Bo

**Comment by srobb1** [comment]
Did you `git add oops` ?

**Comment by TheophilusZhang** [comment]
I forgot...

**Comment by TheophilusZhang** [comment]
I forgot...Thanks!
